# Generated by Django 3.1.3 on 2021-03-30 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
