# Generated by Django 3.1.3 on 2021-03-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20210330_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_created=True)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='announcements.event')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
