# Generated by Django 3.1.3 on 2021-04-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20210402_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_request',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
