# Generated by Django 3.1.3 on 2021-04-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20210405_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='student_id',
        ),
    ]
