# Generated by Django 3.1.3 on 2021-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20210413_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMAGES',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
