# Generated by Django 3.1.3 on 2021-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMAGES',
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
