# Generated by Django 3.1.3 on 2021-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20210425_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_picture',
            field=models.ImageField(blank=True, upload_to='club_uploads/'),
        ),
    ]
